config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/new', to: 'dashboard#new'

  match '/logout', to: 'sessions#destroy',     via: ['delete', 'get']
  match '/login', to: 'sessions#create',     via: 'post'

  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :elections, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :events, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :photos, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :articles, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :polls, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :photo_albums, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :positions, only: [:create, :update, :destroy, :index]
  resources :tickets, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :candidates, only: [:create, :update, :destroy, :new, :edit, :index]

  root 'home#landing'

  get 'home', to: 'home#landing'
  get 'home/more_info'
  get 'home/signup'
  get 'about', to: 'home#about'
  get 'details', to: 'home#details'
  get 'signin', to: 'home#signin'
  get 'home/unverified_email'
  get 'home/register_successfull'
  get 'home/landing'
  
  get 'error/general_error'
  
  post 'home/signup_user', :to => 'home#signup_user', :as => :home_signup_user
  put 'user/resend_verification_email/:id(.:format)', :to => 'user#resend_verification_email', :as => :user_resend_verification_email
  post 'articles/picture/:id(.:format)', :to => 'articles#upload_picture', :as => :article_upload_picture
  delete 'articles/picture/:id(.:format)', :to => 'articles#delete_picture', :as => :article_delete_picture
  post 'events/picture/:id(.:format)', :to => 'events#upload_picture', :as => :event_upload_picture
  delete 'events/picture/:id(.:format)', :to => 'events#delete_picture', :as => :event_delete_picture
  post 'photo_albums/picture/:id(.:format)', :to => 'photo_albums#upload_picture', :as => :photo_album_upload_picture
  delete 'photo_albums/picture/:id(.:format)', :to => 'photo_albums#delete_picture', :as => :photo_album_delete_picture

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #Set the default layout for this controller, the views from this controller are available when the user is looged in
  layout 'application'
  @@images_directory = "UniversityOfMelbourne/NewsArticles"

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to retrieve and list all the articles from the model by its owner id
--------------------------------------------------------------------------------------------------------------------------------
=end
  def index
    @menu='articles' #Set the menu variable
    $title=t(:title_articles)  #Set the title variable
    if !check_session #Validate if the user session is active
	    return #If not force return to trigger the redirect of the check_session function
	  end
	  @page_aux = params[:page] #Retrieve the params from the query string
	  @page = @page_aux =~ /\A\d+\z/ ? @page_aux.to_i : 0  #Validate if the page_aux param can be parsed as an integer, otherwise set it to cero
	  resp = Article.all(session[:user],@page) #Retrieve all the articles from the model
	  if resp[0] #Validate if the response was successfull
	    @articles_list = resp[1] #Get the article list from the response
	    @total_pages = resp[3].to_i #Get the total numer of pages from the response
	    @previous_page = @page > 0 ? @page-1 : -1 #Calculate the previous page number, if we are at the first page, then it will set to minus one
	    @next_page = @page+1 < @total_pages ? @page+1 : -1 #Calculate the next page number, if we are at the last page, then it will set to minus one
	  elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
	    flash[:danger] = t(:article_list_error_flash) #Set the error message to the user
	    redirect_to error_general_error_path #Redirect the user to the generic error page
	  else
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)	
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to redirect the user to the new article page
--------------------------------------------------------------------------------------------------------------------------------
=end
  def new
    @menu='articles' #Set the menu variable
    $title=t(:title_new_article)  #Set the title variable
    if !check_session #Validate if the user session is active
	    return #If not force return to trigger the redirect of the check_session function
	  end
	  @article = Article.new #Set a new article object to be filled by the user form
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to redirect the user to the edit article page
--------------------------------------------------------------------------------------------------------------------------------
=end
  def edit
    @menu='articles' #Set the menu variable
    $title=t(:title_edit_article)  #Set the title variable
    if !check_session #Validate if the user session is active
  	  return #If not force return to trigger the redirect of the check_session function
	  end
	  resp = Article.find(params[:id],session[:user]) #Retrieve the article to update
	  if resp[0] #Validate if the response was successfull
	    @article = resp[1] #Set the article object to fill the edit form
	  elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
	    flash[:danger] = t(:article_get_error_flash) #Set the error message for the user
	    redirect_to articles_path #Redirect the user to edit article page
	  else 
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to create a new Article
--------------------------------------------------------------------------------------------------------------------------------
=end
  def create
    if !check_session #Validate if the user session is active
	    return #If not force return to trigger the redirect of the check_session function
	  end
	  @article = Article.new(article_params) #Create a new article object with the parameters set by the user in the create form
	  @article.creator_email = session[:user]['email'] #Set the creator email to the looged user email
    resp = @article.save(session[:user]) #Save the new Article object

	  if resp[0] #Validate if the response was successfull
	    @article = resp[1] #Get the article object from the server response
	    if !resp[2] #Validate if the photo creation was successfull
	      flash[:warning] = t(:article_photo_creation_error_flash) #Set the error message for the user
	    end
	    flash[:success] = t(:article_creation_success_flash, article: @article.title) #Set the success message for the user
      redirect_to articles_path and return #Redirect the user to the articles list page
      
	  elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
	    if(resp[1].kind_of?(Array)) #If the response was unsucessful, validate if it was caused by an invalid Article object sent to the model. If so the server would have returned an array with the errors
        flash[:warning] = Util.format_validation_errors(resp[1]) #Set the invalid object message for the user
      end
      flash[:danger] = t(:article_creation_error_flash) #Set the error message for the user
      redirect_to articles_path and return
      # @article = Article.new  #Reset the Article object to an empty one
      # redirect_to new_article_path #Redirect the user to the Article creation page
	  else 
      return #If not force return to trigger the redirect of the check_session function
    end

    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to update an Article
--------------------------------------------------------------------------------------------------------------------------------
=end
def update
  if !check_session #Validate if the user session is active
    return #If not force return to trigger the redirect of the check_session function
  end
  resp = Article.find(params[:id],session[:user]) #Retrieve the original article object to update
  if resp[0] #Validate if the response was successfull
    @article = resp[1] #Set the article object to be updated
  elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
    flash[:danger] = t(:article_get_error_flash) #Set the error message for the user
    redirect_to articles_path #Redirect the user to the articles list page
  else 
    return #If not force return to trigger the redirect of the check_session function
  end
  resp2 = @article.update_attributes(article_params,session[:user]) #Update the article object
  if resp2[0] #Validate if the response was successfull
    flash[:success] = t(:article_modification_success_flash, article: @article.title) #Set the success message for the user
    redirect_to articles_path #Redirect the user to the articles list page
  elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
    if(resp[1].kind_of?(Array)) #If the response was unsucessful, validate if it was caused by an invalid Article object sent to the model. If so the server would have returned an array with the errors
      flash[:warning] = Util.format_validation_errors(resp[1]) #Set the invalid object message for the user
    end
    flash[:danger] = t(:article_modification_error_flash) #Set the error message for the user
    redirect_to edit_article_path #Redirect the user to the Article edition page
  else 
    return #If not force return to trigger the redirect of the check_session function
  end
  rescue #Error Handilng code
    general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to upload a picture owned by an article
--------------------------------------------------------------------------------------------------------------------------------
=end
def upload_picture
  if !check_session #Validate if the user session is active
    return #If not force return to trigger the redirect of the check_session function
  end
  resp = Article.find(params[:id],session[:user]) #Retrieve the original article object to update
  if resp[0] #Validate if the response was successfull
	  @article = resp[1] #Set the article object to be updated
  elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
    flash[:danger] = t(:article_get_error_flash) #Set the error message for the user

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<% provide(:title, t(:title_edit_article)) %>

<header 
class="title_photoheader"
  <% if @article.picture[0] %>
  style="background: url(<%= @article.picture[0]["url"] %>);"
  <% end %>
  />
  <div class="title_menubar">
    <%= form_for(@article, :url => article_upload_picture_path ,:html => {:method => :post}) do |photo_f| %>
      <%= photo_f.file_field :picture, accept: "image/png,image/gif,image/jpeg" ,class: 'file_input_control', placeholder: t(:field_placeholder, field_name: t(:picture)).capitalize %>
      <button class="UI button capsule dark item" name="Publish">Upload Photo</button>
    <% end %>

    <% if false %>
      <button class="UI button capsule dark item" name="Publish">Clear Photo</button>
      <button class="UI button capsule dark item" name="Publish" style="margin-left: auto;">Delete</button>
      <button class="UI button capsule dark item" name="Publish">Save to Queue</button>
      <button class="UI button capsule dark item" name="Publish">Publish</button>
    <% end %>
  </div>
  <%= form_for(@article, :url => article_path ,:html => {:method => :put}) do |f| %>
  <%= f.text_field :title, class: "UI editfield header transparent", style: "width: 80%; max-width: 560px;", placeholder: t(:field_placeholder, field_name: t(:title)).capitalize %>
</header> 

<div class="page_container">
  <nav class="menubar">
    <% if false %>
      <div class="item" style="">
        <button class="UI button fullheight blue" name="Button">Add Quotation</button>
        <button class="UI button fullheight blue" name="Button">Add Poll</button>
      </div>
    <% end %>

    <div class="item" style="margin-left: auto;">
      <input
        class="UI button fullheight green"
        type="submit"
        value="<% if action_name == 'edit' %>Finish Editing<% else %>Publish<% end %>"
        name="commit" />
    </div>
  </nav>

  <% if false %>
    <div class="UI separator light">
      <h6 style="margin-right:auto;">Subheader</h6>
      <% if false %><h6>250/500 Words</h6><% end %>
    </div>
    <input class="UI editfield subheader" style="width:100%;" type="text" value="Document Subheader">
  <% end %>

  <div class="UI separator light">
    <h6 style="margin-right:auto;">Body Text</h6>
    <% if false %><h6>250/1500 Words</h6><% end %>
  </div>
  <%= f.text_area :content, class: "UI editfield body", style: "width: 100%; min-height: 250px;", placeholder: t(:field_placeholder, field_name: t(:content)).capitalize %>
</div>
<% end %>

<%= javascript_include_tag "articles_util" %>
<script type="text/javascript">
  $("#dpk_date").datepicker({
    format: '<%=t(:date_format_javascript)%>',
    todayBtn: 'linked',
    autoclose: true
  });
</script>





<% if false %>

<div>
<%= form_for(@article, :url => article_path ,:html => {:method => :put}) do |f| %>
<div id="form_header_background"></div>
  <div id="form_header">
    <div id="form_header_top">
      <%= link_to image_tag("home/Camera.png", alt:t(:choose_cover_back)) + capitalize_as_title(t(:choose_cover_back)) , '#', :class => "btn btn_choose_cover" %>
      <%= f.submit capitalize_as_title(t(:save_and_finish)), class: "btn btn-form btn_form_header" %>
    </div>
    <hr>
    <%= f.text_field :title, class: "form-control text_field title_text_field", placeholder: t(:field_placeholder, field_name: t(:title)).capitalize %>
  </div>
  <div id="form_main">
    <div class="form-group">
      <label class="form-field-label"><%=capitalize_as_title(t(:date))%></label>
      <hr class="form-field-hr">
      <div class="input-group date" id="dpk_date" >
        <span class="input-group-addon input-addon-left">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
        <input type="text" class="form-control date_field" placeholder="<%=t(:field_placeholder, field_name: t(:date)).capitalize%>" name="article[date]" value="<%=@article.date%>" readonly>
      </div>
    </div>
    <div class="form-group">
      <label class="form-field-label"><%=capitalize_as_title(t(:content))%></label>
      <hr class="form-field-hr">
      <%= f.text_area :content, class: "text_area form-control", placeholder: t(:field_placeholder, field_name: t(:content)).capitalize %>
    </div>
    <% end %>
    <br>
  </div>
  <div id="upload_pic_form">
    <%= form_for(@article, :url => article_upload_picture_path ,:html => {:method => :post}) do |f| %>
      <div class="form-group">
        <label class="form-field-label"><%=capitalize_as_title(t(:picture))%></label>
        <hr class="form-field-hr">
        <% @article.picture.each do |picture| %>
          <%= image_tag picture["url"], class: "article_image"%>
          <%= link_to t(:delete).capitalize, article_delete_picture_path(:id => picture["nodeId"]), method: :delete, :class => 'delete_link' %>
        <%end%>
      </div>
      <input type="hidden" id="hdd_previous_picture" name="article[previous_picture]" value="<%=@article.picture.blank? ? nil : @article.picture[0].to_json%>">
      <div class="form-group">
        <label class="form-field-label"><%=capitalize_as_title(t(:upload_new_picture))%></label>
        <hr class="form-field-hr">
        <div class="file_input_wrapper">
          <%= f.file_field :picture, accept: "image/png,image/gif,image/jpeg" ,class: 'file_input_control', placeholder: t(:field_placeholder, field_name: t(:picture)).capitalize %>
          <input class="btn btn-form file_input_button" type="button" value="<%=capitalize_as_title(t(:browse)) %>" name="commit">
        </div>
      </div>
      <div class="upload-preview">
        <!--label class="form-field-label"><%=capitalize_as_title(t(:picture_preview))%></label-->
        <!--Image closing tag required by the upload-preview-->
        <img />
      </div>
      <%= f.submit capitalize_as_title(t(:upload)), class: "btn btn-form file_input_button" %>
  <% end %>
  </div>
</div>

<% end %>

app/views/articles/index.html.erb
<div id="articles_list">
  <% @articles_list.each do |article| %>

    <section class="module news">
      <div class="module_container">
        <div class="module_media">
          <%= image_tag article.picture.blank? ? GENERIC_ARTICLE_IMAGE : article.picture[0]["url"], class: "img_tile", alt: t(:picture) %>
        </div>      
        <div class="module_text">
          <h3><%= article.title %></h3>
          <h4><%= article.date %></h4>

          <hr style="visibility: hidden;">

          <ul>
            <li>Added by <%= article.creatorProfile["givenName"] %> <%= article.creatorProfile["familyName"] %></li>
          </ul>
        </div>
        <%= button_to '', article_path(:id => article.id), confirm: 'Are you sure?', method: :delete, class: "UI button icon delete red" %>
        <%= link_to '<button class="UI button icon info blue" name="Button"></button>'.html_safe, edit_article_path(:id => article.id) %>
      </div>
    </section>

  <% end %>
</div>

app/views/articles/new.html.erb
<% provide(:title, t(:title_edit_article)) %>

<%= form_for(@article) do |f| %>

<header 
  class="title_photoheader" />  
    <%= f.file_field :picture, accept: "image/png,image/gif,image/jpeg" ,class: 'file_input_control', placeholder: t(:field_placeholder, field_name: t(:picture)).capitalize %>
    <div class="title_menubar">
      <button id="upload-photo" class="UI button capsule dark item" name="commit">Upload Photo</button>
      <div class="upload-preview" style="display: none;">
        <!--label><%=capitalize_as_title(t(:picture_preview))%></label-->
        <!--Image closing tag required by the upload-preview-->
        <img />
      </div>
      
      <% if false %>
        <button class="UI button capsule dark item" name="Publish">Clear Photo</button>
        <button class="UI button capsule dark item" name="Publish" style="margin-left: auto;">Delete</button>
        <button class="UI button capsule dark item" name="Publish">Save to Queue</button>
        <button class="UI button capsule dark item" name="Publish">Publish</button>
      <% end %>
  </div>
        
  <%= f.text_field :title, class: "UI editfield header", style: "width: 80%; max-width: 560px;", placeholder: t(:field_placeholder, field_name: t(:title)).capitalize %>
</header> 

<div class="page_container">
  <nav class="menubar">
    <% if false %>
      <div class="item" style="">
        <button class="UI button fullheight blue" name="Button">Add Quotation</button>
        <button class="UI button fullheight blue" name="Button">Add Poll</button>
      </div>
    <% end %>

    <div class="item" style="margin-left: auto;">
      <input
        class="UI button fullheight green"
        type="submit"
        value="<% if action_name == 'edit' %>Finish Editing<% else %>Publish<% end %>"
        name="commit" />
    </div>
  </nav>

  <% if false %>
    <div class="UI separator light">
      <h6 style="margin-right:auto;">Subheader</h6>
      <% if false %><h6>250/500 Words</h6><% end %>
    </div>
    <input class="UI editfield subheader" style="width:100%;" type="text" value="Document Subheader">
  <% end %>

  <div class="UI separator light">
    <h6 style="margin-right:auto;">Date</h6>
  </div>
  <div class="input-group date" id="dpk_date" >
    <span class="input-group-addon input-addon-left">
      <i class="glyphicon glyphicon-calendar"></i>
    </span>
    <input type="text" style="border: none; font-size: 125%;" readonly="true" class="form-control date_field" value="<%= Time.now.strftime("%d %B %Y") %>" placeholder="<%=t(:field_placeholder, field_name: t(:date)).capitalize%>" name="article[date]">
  </div>

  <div class="UI separator light">
    <h6 style="margin-right:auto;">Body Text</h6>
    <h6><span class="body-wc">0</span>/1500 Words</h6>
  </div>
  <%= f.text_area :content, class: "UI editfield body", style: "width: 100%; min-height: 250px;", placeholder: t(:field_placeholder, field_name: t(:content)).capitalize %>
</div>
<% end %>

<%= javascript_include_tag "articles_util" %>
<script type="text/javascript">
  $("#dpk_date").datepicker({
    format: '<%=t(:date_format_javascript)%>',
    todayBtn: 'linked',
    autoclose: true
  });
</script>



<% if false %>
<% provide(:title, t(:title_new_article)) %>
<div>
<%= form_for(@article) do |f| %>
  <div id="form_header_background"></div>
  <div id="form_header">
    <div id="form_header_top">
    <%= link_to image_tag("home/Camera.png", alt:t(:choose_cover_back)) + capitalize_as_title(t(:choose_cover_back)) , '#', :class => "btn btn_choose_cover" %>
    <%= f.submit capitalize_as_title(t(:save_and_finish)), class: "btn btn-form btn_form_header" %>
    </div>
    <hr>
    <%= f.text_field :title, class: "form-control text_field title_text_field", placeholder: t(:field_placeholder, field_name: t(:title)).capitalize %>
  </div>
  <div id="form_main">
  <div class="form-group">
    <label class="form-field-label"><%=capitalize_as_title(t(:date))%></label>
    <hr class="form-field-hr">
    <div class="input-group date" id="dpk_date" >
      <span class="input-group-addon input-addon-left">
        <i class="glyphicon glyphicon-calendar"></i>
      </span>
      <input type="text" readonly="true" class="form-control date_field" placeholder="<%=t(:field_placeholder, field_name: t(:date)).capitalize%>" name="article[date]">
    </div>
  </div>
  <div class="form-group">
    <label class="form-field-label"><%=capitalize_as_title(t(:content))%></label>
    <hr class="form-field-hr">
    <%= f.text_area :content, class: "form-control text_area", placeholder: t(:field_placeholder, field_name: t(:content)).capitalize %>
  </div>
  <div class="form-group">
      <%= f.label :picture, capitalize_as_title(t (:picture)), class: "form-field-label" %> 
      <hr class="form-field-hr">
    <div class="file_input_wrapper">
      <%= f.file_field :picture, accept: "image/png,image/gif,image/jpeg" , placeholder: t(:field_placeholder, field_name: t(:picture)).capitalize, class: 'file_input_control' %>
      <input class="btn btn-form file_input_button" type="button" value="<%=capitalize_as_title(t(:browse)) %>" name="commit">
    </div>
  </div>
  <div class="upload-preview">
    <!--label><%=capitalize_as_title(t(:picture_preview))%></label-->
    <!--Image closing tag required by the upload-preview-->
    <img />
  </div>
  </div>
  <% end %>
</div>
<%= javascript_include_tag "articles_util" %>
<script type="text/javascript">
  $("#dpk_date").datepicker({
    format: '<%=t(:date_format_javascript)%>',
    todayBtn: 'linked',
    autoclose: true
  });
</script>

<% end %>