config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/new', to: 'dashboard#new'

  match '/logout', to: 'sessions#destroy',     via: ['delete', 'get']
  match '/login', to: 'sessions#create',     via: 'post'

  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :elections, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :events, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :photos, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :articles, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :polls, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :photo_albums, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :positions, only: [:create, :update, :destroy, :index]
  resources :tickets, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :candidates, only: [:create, :update, :destroy, :new, :edit, :index]

  root 'home#landing'

  get 'home', to: 'home#landing'
  get 'home/more_info'
  get 'home/signup'
  get 'about', to: 'home#about'
  get 'details', to: 'home#details'
  get 'signin', to: 'home#signin'
  get 'home/unverified_email'
  get 'home/register_successfull'
  get 'home/landing'
  
  get 'error/general_error'
  
  post 'home/signup_user', :to => 'home#signup_user', :as => :home_signup_user
  put 'user/resend_verification_email/:id(.:format)', :to => 'user#resend_verification_email', :as => :user_resend_verification_email
  post 'articles/picture/:id(.:format)', :to => 'articles#upload_picture', :as => :article_upload_picture
  delete 'articles/picture/:id(.:format)', :to => 'articles#delete_picture', :as => :article_delete_picture
  post 'events/picture/:id(.:format)', :to => 'events#upload_picture', :as => :event_upload_picture
  delete 'events/picture/:id(.:format)', :to => 'events#delete_picture', :as => :event_delete_picture
  post 'photo_albums/picture/:id(.:format)', :to => 'photo_albums#upload_picture', :as => :photo_album_upload_picture
  delete 'photo_albums/picture/:id(.:format)', :to => 'photo_albums#delete_picture', :as => :photo_album_delete_picture

end

app/views/partials/_admin_list_pagination.html.erb
<% if @total_pages %>
<div class="pagination_controls">
  <% if @previous_page >=0 %>
    <%= link_to "<<", articles_path(:page =>@previous_page), :class => 'nav_control' %>
  <%end%>

  <span class="page_number">Page <%=(@page+1)%> of <%=@total_pages%></span>

  <% if @next_page >=0 %>
    <%= link_to ">>", articles_path(:page =>@next_page), :class => 'nav_control' %>
  <%end%>
</div>
<% end %>

app/views/partials/_color_picker.html.erb
<table>
  <tr>
    <td class="color_cell" >
      <input type="button" class="color_cell_button" style="background-color: #FF0000; color:#FF0000" value="#FF0000">
    </td>
    <td class="color_cell" >
    <input type="button" class="color_cell_button" style="background-color: #006633; color:#006633" value="#006633">
    </td>
    <td class="color_cell" >
    <input type="button" class="color_cell_button" style="background-color: #0000FF; color:#0000FF" value="#0000FF">
    </td>
    <td class="color_cell">
    <input type="button" class="color_cell_button" style="background-color: #6600FF; color:#6600FF" value="#6600FF">
    </td>
    <td class="color_cell">
    <input type="button" class="color_cell_button" style="background-color: #000000; color:#000000" value="#000000">
    </td>
  </tr>
  <tr>
    <td class="color_cell" >
      <input type="button" class="color_cell_button" style="background-color: #FF9900; color:#FF9900" value="#FF9900">
    </td>
    <td class="color_cell" >
    <input type="button" class="color_cell_button" style="background-color: #009933; color:#009933" value="#009933">
    </td>
    <td class="color_cell" >
    <input type="button" class="color_cell_button" style="background-color: #0066FF; color:#0066FF" value="#0066FF">
    </td>
    <td class="color_cell">
    <input type="button" class="color_cell_button" style="background-color: #9900FF; color:#9900FF" value="#9900FF">
    </td>
    <td class="color_cell">
    <input type="button" class="color_cell_button" style="background-color: #666666; color:#666666" value="#666666">
    </td>
  </tr>
  <tr>
    <td class="color_cell" >
      <input type="button" class="color_cell_button" style="background-color: #FFCC00; color:#FFCC00" value="#FFCC00">
    </td>
    <td class="color_cell" >
    <input type="button" class="color_cell_button" style="background-color: #00CC33; color:#00CC33" value="#00CC33">
    </td>
    <td class="color_cell" >
    <input type="button" class="color_cell_button" style="background-color: #0099FF; color:#0099FF" value="#0099FF">
    </td>
    <td class="color_cell">
    <input type="button" class="color_cell_button" style="background-color: #9966FF; color:#9966FF" value="#9966FF">
    </td>
    <td class="color_cell">
    <input type="button" class="color_cell_button" style="background-color: #AAAAAA; color:#AAAAAA" value="#AAAAAA">
    </td>
  </tr>
  <tr>
    <td class="color_cell" >
      <input type="button" class="color_cell_button" style="background-color: #FFFF00; color:#FFFF00" value="#FFFF00">
    </td>
    <td class="color_cell" >
    <input type="button" class="color_cell_button" style="background-color: #00FF33; color:#00FF33" value="#00FF33">
    </td>
    <td class="color_cell" >
    <input type="button" class="color_cell_button" style="background-color: #00FFFF; color:#00FFFF" value="#00FFFF">
    </td>
    <td class="color_cell">
    <input type="button" class="color_cell_button" style="background-color: #FF66FF; color:#FF66FF" value="#FF66FF">
    </td>
    <td class="color_cell">
    <input type="button" class="color_cell_button" style="background-color: #FFFFFF; color:#FFFFFF" value="#FFFFFF">
    </td>
  </tr>
</table>

app/views/partials/_facebook_SDK.html.erb
<script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '<%= FB_APP_ID%>',
          xfbml      : true,//Set to true if you have socia plugins loaded with xfbml
          //xfbml      : false,
          version    : 'v2.0'
        });
        console.log("FB Object initiated");
        FB.XFBML.parse(); // now we can safely call parse method
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         //js.src = "//connect.facebook.net/en_US/sdk.js";//minified version
         js.src = "//connect.facebook.net/en_US/sdk/debug.js";//debug version
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
</script>

app/views/partials/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> fade in" role="alert">
    <button class="close" data-dismiss="alert" type="button">
      <span aria-hidden="true">×</span>
      <span class="sr-only">Close</span>
    </button>
    <strong>
   	  <% case key %>
	  <% when "success" %>
        <%= t(:alert_success_start)%>
      <% when "info" %>
        <%= t(:alert_info_start)%>
      <% when "warning" %>
        <%= t(:alert_warning_start)%>
      <% when "danger" %>
        <%= t(:alert_danger_start)%>
      <% end %>
    </strong>
    <%= value %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer>
  <p>Euler's Bridge© 2014</p>
</footer>

app/views/partials/_googleMaps_API.html.erb
<script type="text/javascript"
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAUnBzbT5A4Idsft5hzl05pD83vXv3Ryk">
</script>

app/views/partials/_header_in.html.erb
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top_navbar">
      <span class="sr-only"><%=capitalize_as_title(t(:toggle_navigation))%></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to image_tag("navigation/Home.png", alt:t(:app_name) + t(:home)), events_path, :class => " isegoria_navbar_link navbar-left" %>
    <%= link_to image_tag("navigation/Back.png", alt:t(:app_name) + t(:back)) + t(:back).capitalize , :back, :class => "isegoria_navbar_link navbar-left" %>
    <% if controller.action_methods.include?('new') %>
      <%= link_to image_tag("navigation/PlusNav.png", alt:t(:create_article)) + t(:create).capitalize, {:action => :new}, :class=>'isegoria_navbar_link navbar-left'%>
    <% end %>
  </div>
  <div class="navbar-collapse collapse" id="top_navbar">
    <%= link_to image_tag("navigation/Log Off.png", alt:t(:logout)), logout_path, method: :delete, :class => "navbar-right isegoria_navbar_link" %>
    <%= link_to image_tag("navigation/Notifications.png", alt:t(:notifications)), '#', :class => "navbar-right isegoria_navbar_link" %>
    <%= link_to image_tag("navigation/Activity.png", alt:t(:activity)), '#', :class => "navbar-right isegoria_navbar_link" %>
    <span class="isegoria_navbar_title navbar-left">
      <%=capitalize_as_title($title)%>
    </span>
  </div><!--/.navbar-collapse -->
</div>

app/views/partials/_header_off.html.erb
<div id="header">
<!--div class="navbar navbar-inverse navbar-fixed-top" role="navigation"-->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only"><%=capitalize_as_title(t(:toggle_navigation))%></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand visible-xs" href="/"><%=image_tag("isegoria-logo-xs.jpg", alt:t(:app_name) + t(:logo))%> <%=t(:app_name)%></a>
      <a class="navbar-brand visible-sm" href="/"><%=image_tag("isegoria-logo-sm.jpg", alt:t(:app_name) + t(:logo))%> <%=t(:app_name)%></a>
      <a class="navbar-brand hidden-xs hidden-sm" href="/"><%=image_tag("Eulers_Logo_White_50.png", alt:t(:app_name) + t(:logo))%> <%=t(:app_name)%></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#"><%=t(:introduction).capitalize%></a></li>
        <li><a href="#"><%=t(:benefits).capitalize%></a></li>
        <li><a href="#"><%=capitalize_as_title(t(:show_cases))%></a></li>
      </ul>
      <%= form_for(:session, url: sessions_path, :html =>{class: "navbar-form navbar-right"}) do |f| %>
        <div class="form-group">
          <%= f.label :username, t(:username).capitalize, class: "sr-only" %>
          <%= f.text_field :username, class: "form-control", placeholder: t(:username).capitalize %>
        </div>
        <div class="form-group">
          <%= f.label :password, t(:password).capitalize, class: "sr-only" %>
          <%= f.password_field :password, class: "form-control", placeholder: t(:password).capitalize %>
        </div>
        <%= f.submit capitalize_as_title(t(:login)), class: "btn btn-info navbar-button" %>
      <% end %>
    </div><!--/.navbar-collapse -->
  </div>
<!--/div-->
</div>

app/views/partials/_landing_footer.html.erb
<div id= "landing_container_footer" class="landing_container">
  <div id="landing_footer" class="landing-section row">    
    <div id="landing_footer_links_bar">
      <div id="landing_footer_links" class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
        <%= link_to capitalize_as_title(t(:home)),home_path,:class => "btn"%>
        <%= link_to capitalize_as_title(t(:about_us)),home_more_info_path,:class => "btn"%>
        <%= link_to capitalize_as_title(t(:terms_of_service)),home_details_path(:anchor => "terms_of_service_anchor"),:class => "btn"%>
        <a href="mailto:contact@eulersbridge.com?Subject=contacting%20eulers%20bridge" class="btn" target="_top"><%=capitalize_as_title(t(:contact_us))%></a>
      </div>

      <div id="landing_footer_icons" class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <a class="btn" href="https://www.facebook.com/isegoria.community">
          <%=image_tag("landing/Facebook.png", alt:t(:app_name))%></a>
        <a class="btn" href="https://twitter.com/EulersBridge">
          <%=image_tag("landing/Twitter.png", alt:t(:app_name))%></a>
        <a class="btn" href="https://www.youtube.com/channel/UCLneRR6lG5GBHZbAtWLSLgA">
          <%=image_tag("landing/Youtube.png", alt:t(:app_name))%></a>
      </div>

      <div class="clearfix"></div>
    </div>
    <hr>
    <h5 class="copyright"><%=t(:copyright_text)%></h5>
  </div>
</div>

app/views/partials/_main_menu.html.erb
<section class="item">
  <header>
    <h3><%= t(:news_feed).capitalize %></h3>
  </header>

  <!--<%= link_to t(:news_feed).capitalize, events_path %>-->
  <%= link_to t(:articles).capitalize, articles_path %>
  <%= link_to t(:photos).capitalize, photos_path %>
  <%= link_to t(:events).capitalize, events_path %>
</section>


<% if false %>
<section class="item">
  <header>
    <h3><%= t(:election).capitalize %></h3>
  </header>

  <%= link_to t(:positions).capitalize, positions_path %>
  <%= link_to t(:tickets).capitalize, tickets_path %>
  <%= link_to t(:candidates).capitalize, candidates_path %>
</section>
<% end %>

app/views/partials/_map.html.erb
    <script type="text/javascript">
    <% if (defined?(marker_image)).nil?
        @image = MAP_MARKER_IMAGE
      else
        @image = marker_image
      end
      if (defined?(map_class)).nil?
        @map_class = ''
      else
        @map_class = map_class
      end
      if (defined?(map_id)).nil?
        console.log('Error, no map Id provided')
      end
    %>
      $(function () {
        var myLatlng = new google.maps.LatLng(<%=latitude%>,<%=longitude%>);
        //var image = '/pin-marker.png';
        // Origins, anchor positions and coordinates of the marker
      // increase in the X direction to the right and in
      // the Y direction down.
      var image = {
          url: '<%=@image%>',
          // This marker is 20 pixels wide by 32 pixels tall.
          //size: new google.maps.Size(200, 200),
          // The origin for this image is 0,0.
          //origin: new google.maps.Point(0,0),
          // The anchor for this image is the base of the flagpole at 0,32.
          //anchor: new google.maps.Point(0, 32)
        };

        var mapOptions = {
          center: myLatlng,
          zoom: 17
        };
        var map = new google.maps.Map(document.getElementById('<%=map_id%>'), mapOptions);
        
      // To add the marker to the map, use the 'map' property
      var marker = new google.maps.Marker({
      position: myLatlng,
      title:'<%=@title%>',
      animation: google.maps.Animation.DROP,
      icon: image
      });
      // To add the marker to the map, call setMap();
      marker.setMap(map);
      console.log(image);
      });
      //google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div id='<%=map_id%>' style="height: 500px; width:500px;" class='<%=@map_class%>'/>