config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/new', to: 'dashboard#new'

  match '/logout', to: 'sessions#destroy',     via: ['delete', 'get']
  match '/login', to: 'sessions#create',     via: 'post'

  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :elections, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :events, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :photos, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :articles, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :polls, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :photo_albums, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :positions, only: [:create, :update, :destroy, :index]
  resources :tickets, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :candidates, only: [:create, :update, :destroy, :new, :edit, :index]

  root 'home#landing'

  get 'home', to: 'home#landing'
  get 'home/more_info'
  get 'home/signup'
  get 'about', to: 'home#about'
  get 'details', to: 'home#details'
  get 'signin', to: 'home#signin'
  get 'home/unverified_email'
  get 'home/register_successfull'
  get 'home/landing'
  
  get 'error/general_error'
  
  post 'home/signup_user', :to => 'home#signup_user', :as => :home_signup_user
  put 'user/resend_verification_email/:id(.:format)', :to => 'user#resend_verification_email', :as => :user_resend_verification_email
  post 'articles/picture/:id(.:format)', :to => 'articles#upload_picture', :as => :article_upload_picture
  delete 'articles/picture/:id(.:format)', :to => 'articles#delete_picture', :as => :article_delete_picture
  post 'events/picture/:id(.:format)', :to => 'events#upload_picture', :as => :event_upload_picture
  delete 'events/picture/:id(.:format)', :to => 'events#delete_picture', :as => :event_delete_picture
  post 'photo_albums/picture/:id(.:format)', :to => 'photo_albums#upload_picture', :as => :photo_album_upload_picture
  delete 'photo_albums/picture/:id(.:format)', :to => 'photo_albums#delete_picture', :as => :photo_album_delete_picture

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #Set the default layout for this controller, the views from this controller are available when the user is looged in
  layout 'application'

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to sign up a new User, created without being logged in
--------------------------------------------------------------------------------------------------------------------------------
=end
  def signup
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    @user = User.new(user_params) #Create a new User object with the parameters set by the user in the create form
    response = @user.save #Save the new User object
    if response[0] #Validate if the response was successfull
      flash[:success] = t(:user_creation_success_flash, user: @user.email) #Set the success message for the user
      redirect_to home_unverified_email_path #Redirect the user to the verify email
    elsif validate_authorized_access(response[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      if(response[1].kind_of?(Array)) #If the response was unsucessful, validate if it was caused by an invalid photo album object sent to the model. If so the server would have returned an array with the errors
        flash[:warning] = Util.format_validation_errors(response[1]) #Set the invalid object message for the user
      end
      flash[:danger] = t(:user_creation_error_flash) #Set the error message for the user
      redirect to register_successfull_path, layout: "logged_off"
    else
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to retrieve and list all the users from the model
--------------------------------------------------------------------------------------------------------------------------------
=end
  def index
    @menu='users'
    $title=t(:title_users_list)
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    page_aux = params[:page] #Retrieve the params from the query string
    @page = page_aux =~ /\A\d+\z/ ? page_aux.to_i : 0 #Validate if the page_aux param is turnable to an integer, otherwise set it to cero
    response = User.all(session[:user],@page) #Retrieve all the users from the model
    if response[0] #Validate if the response was successfull
      @users_list = response[1] #Get the users list from the response
      total_pages = response[3].to_i #Get the total numer of pages from the response
      @previous_page = @page > 0 ? @page-1 : -1 #Calculate the previous page number, if we are at the first page, then it will set to minus one
      @next_page = @page+1 < total_pages ? @page+1 : -1 #Calculate the next page number, if we are at the last page, then it will set to minus one
    elsif validate_authorized_access(response[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      flash[:danger] = t(:user_list_error_flash) #Set the error message to the user
      redirect_to error_general_error_path #Redirect the user to the generic error page
    else
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to redirect the user to the new user page
--------------------------------------------------------------------------------------------------------------------------------
=end
  def new
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    @user = User.new #Set a new user object to be filled with the create form
    response = Country.general_info #Retrieve the countries and institutions catalog
    if response[0] #Validate if the response was successfull
      @countries_catalog = response[1] #Get the countries list from the response
      @countries_js_string = response[2]
    elsif validate_authorized_access(response[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      flash[:danger] = t(:country_list_error_flash) #Set the error message to the user
      redirect_to error_general_error_path #Redirect the user to the generic error page
    else
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to create a new User
--------------------------------------------------------------------------------------------------------------------------------
=end
  def create
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    @user = User.new(user_params) #Create a new User object with the parameters set by the user in the create form
    response = @user.save #Save the new User object
    if response[0] #Validate if the response was successfull
      flash[:success] = t(:user_creation_success_flash, user: @user.email) #Set the success message for the user
      redirect_to users_path #Redirect the user to the user list page
    elsif validate_authorized_access(response[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      if(response[1].kind_of?(Array)) #If the response was unsucessful, validate if it was caused by an invalid photo album object sent to the model. If so the server would have returned an array with the errors
        flash[:warning] = Util.format_validation_errors(response[1]) #Set the invalid object message for the user
      end
      flash[:danger] = t(:user_creation_error_flash) #Set the error message for the user
      @user = User.new #Reset the User object to an empty one
      redirect_to new_user_path #Redirect the user to the User creation page
    else
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to redirect the user to the edit user page
--------------------------------------------------------------------------------------------------------------------------------
=end
  def edit
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    response = User.find(params[:email],session[:user]) #Retrieve the user to update
    if response[0] #Validate if the response was successfull
    @user = response[1] #Set the user object to fill the edit form
    elsif validate_authorized_access(response[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      flash[:danger] = t(:user_get_error_flash) #Set the error message for the user
      redirect_to user_path #Redirect the user to edit user page
    else
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to update a User
--------------------------------------------------------------------------------------------------------------------------------
=end
  def update
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    response = User.find(params[:email],session[:user]) #Retrieve the original user object to update
    if response[0] #Validate if the response was successfull
      @user = response[1] #Set the user object to be updated
    elsif validate_authorized_access(response[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      flash[:danger] = t(:user_get_error_flash) #Set the error message for the user
      redirect_to users_path #Redirect the user to the users list page
    else
      return #If not force return to trigger the redirect of the check_session function
    end
    response2 = @user.update_attributes(user_params,session[:user]) #Update the user object
    if response2[0] #Validate if the response was successfull
      flash[:success] = t(:user_modification_success_flash, user: @user.email) #Set the success message for the user
      redirect_to users_path #Redirect the user to the users list page

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.full_name , class: "gravatar")
  end
end

app/views/users/edit.html.erb
<% provide(:title, t(:title_edit_user)) %>
<h1><%=capitalize_as_title(t(:title_edit_user))%></h1>
<div>
<%= form_for(@user ,:url => user_path ,:html => {:method => :put}) do |f| %>
<%= f.submit capitalize_as_title(t(:save_changes)), class: "btn btn-large btn-success" %>
  <div class="form-group">
    <%= f.label :first_name, capitalize_as_title(t(:first_name)) %>
    <%= f.text_field :first_name, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:first_name)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, capitalize_as_title(t(:last_name)) %>
    <%= f.text_field :last_name, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:last_name)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :gender, capitalize_as_title(t(:gender)) %>
    <%= radio_button_tag("user[gender]", "Female") %>
    <%= label_tag(:gender_female, capitalize_as_title(t(:female))) %>
    <%= radio_button_tag("user[gender]", "Male") %>
    <%= label_tag(:gender_male, capitalize_as_title(t(:male))) %>
  </div>
  <div class="form-group" id="divNationality">
    <label for="slNationality"><%=capitalize_as_title(t(:nationality))%></label>
    <select class="form-control" id="slNationality">
      <option value="0"><%=t(:select_one).capitalize%></option>
      <% @countries_catalog.each do |country| %>
          <option value="<%=country.id%>"><%=country.name%></option>
      <%end%>
    </select>
  </div>
  <div class="form-group">
    <%= f.label :yob, capitalize_as_title(t(:yob)) %>
    <%= f.text_field :yob, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:yob)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :password, capitalize_as_title(t (:password)) %>
    <%= f.password_field :password, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:password)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, capitalize_as_title(t (:password_confirmation)) %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:password_confirmation)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :contact_number, capitalize_as_title(t (:contact_number)) %>
    <%= f.text_field :contact_number, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:contact_number)).capitalize %>
  </div>
  <hr>
  <div class="form-group" id="divInstitutionCountry">
    <label for="slInstitutionCountry"><%=capitalize_as_title(t(:institution_country))%></label>
    <select class="form-control" id="slInstitutionCountry">
      <option value="0"><%=t(:select_one).capitalize%></option>
      <% @countries_catalog.each do |country| %>
          <option value="<%=country.id%>"><%=country.name%></option>
        <%end%>
    </select>
  </div>
  <div class="form-group" id="divInstitutionCountry">
    <label for="slInstitution"><%=capitalize_as_title(t(:institution))%></label>
    <select class="form-control" id="slInstitution" name="user[institution_id]">
      <option value="0"><%=t(:select_one).capitalize%></option>
    </select>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label :tracking_off %>
    <%= f.check_box :tracking_off, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :opt_out_data_collection %>
    <%= f.check_box :opt_out_data_collection, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :email, capitalize_as_title(t(:email))%>
    <%= f.text_field :email, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:email)).capitalize, readonly => true%>
  </div>
  <% end %>
  <div hidden="true">
</div>
<script>
  var countries = <%=raw(@countries_js_string)%>;
  var select_one_text = "<%=t(:select_one).capitalize%>"; 
</script>
<%= javascript_include_tag "users_util" %>

app/views/users/index.html.erb
<div id="users_list">
  <% @users_list.each do |user| %>
  <div class="user_item">
    <div class="item_controls">
      <%= link_to t(:edit).capitalize, edit_user_path(:id => user.email), :class => 'edit_link' %>
      <%= link_to t(:delete).capitalize, user_path(:id => user.email), method: :delete, :class => 'delete_link' %>
    </div>
    <div>
      <h3><%=user.email%></h3>
      <h4><%=t(:full_name).capitalize%>: <%=capitalize_as_title(user.full_name)%></h4>
      <h4><%=t(:email).capitalize%>: <%=user.email%></h4>
      <% if user.account_verified == true %>
        <%=capitalize_as_title(t(:account_verified)) %>
      <% else %>
        <%=capitalize_as_title(t(:account_unverified)) %>
      <%= button_to capitalize_as_title(t(:resend_verify_account_email)), user_resend_verification_email_path(:id => user.email, :action_type => "revoke_access"), method: :post, :class => 'btn btn-success' %>
      <% end %>
    </div>
  </div>
  <!--hr-->
  <% end %>
</div>

<div class="section_controls">
  <%= render "partials/admin_list_pagination" %>
</div>

app/views/users/new.html.erb
<% provide(:title, t(:title_new_user)) %>
<h1><%=capitalize_as_title(t(:title_new_user))%></h1>
<div>
<%= form_for(@user) do |f| %>
<%= f.submit capitalize_as_title(t(:create)), class: "btn btn-large btn-success" %>
  <div class="form-group">
    <%= f.label :first_name, capitalize_as_title(t(:first_name)) %>
    <%= f.text_field :first_name, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:first_name)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, capitalize_as_title(t(:last_name)) %>
    <%= f.text_field :last_name, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:last_name)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :gender, capitalize_as_title(t(:gender)) %>
    <%= radio_button_tag("user[gender]", "Female") %>
    <%= label_tag(:gender_female, capitalize_as_title(t(:female))) %>
    <%= radio_button_tag("user[gender]", "Male") %>
    <%= label_tag(:gender_male, capitalize_as_title(t(:male))) %>
  </div>
  <div class="form-group" id="divNationality">
    <label for="slNationality"><%=capitalize_as_title(t(:nationality))%></label>
    <select class="form-control" id="slNationality">
      <option value="0"><%=t(:select_one).capitalize%></option>
      <% @countries_catalog.each do |country| %>
          <option value="<%=country.id%>"><%=country.name%></option>
      <%end%>
    </select>
  </div>
  <div class="form-group">
    <%= f.label :yob, capitalize_as_title(t(:yob)) %>
    <%= f.text_field :yob, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:yob)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :password, capitalize_as_title(t (:password)) %>
    <%= f.password_field :password, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:password)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, capitalize_as_title(t (:password_confirmation)) %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:password_confirmation)).capitalize %>
  </div>
  <div class="form-group">
    <%= f.label :contact_number, capitalize_as_title(t (:contact_number)) %>
    <%= f.text_field :contact_number, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:contact_number)).capitalize %>
  </div>
  <hr>
  <div class="form-group" id="divInstitutionCountry">
    <label for="slInstitutionCountry"><%=capitalize_as_title(t(:institution_country))%></label>
    <select class="form-control" id="slInstitutionCountry">
      <option value="0"><%=t(:select_one).capitalize%></option>
      <% @countries_catalog.each do |country| %>
          <option value="<%=country.id%>"><%=country.name%></option>
        <%end%>
    </select>
  </div>
  <div class="form-group" id="divInstitutionCountry">
    <label for="slInstitution"><%=capitalize_as_title(t(:institution))%></label>
    <select class="form-control" id="slInstitution" name="user[institution_id]">
      <option value="0"><%=t(:select_one).capitalize%></option>
    </select>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label :tracking_off %>
    <%= f.check_box :tracking_off, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :opt_out_data_collection %>
    <%= f.check_box :opt_out_data_collection, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :email, capitalize_as_title(t(:email))%>
    <%= f.text_field :email, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:email)).capitalize%>
  </div>
  <% end %>
  <div hidden="true">
</div>
<script>
  var countries = <%=raw(@countries_js_string)%>;
  var select_one_text = "<%=t(:select_one).capitalize%>"; 
</script>
<%= javascript_include_tag "users_util" %>