config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/new', to: 'dashboard#new'

  match '/logout', to: 'sessions#destroy',     via: ['delete', 'get']
  match '/login', to: 'sessions#create',     via: 'post'

  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :elections, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :events, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :photos, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :articles, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :polls, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :photo_albums, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :positions, only: [:create, :update, :destroy, :index]
  resources :tickets, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :candidates, only: [:create, :update, :destroy, :new, :edit, :index]

  root 'home#landing'

  get 'home', to: 'home#landing'
  get 'home/more_info'
  get 'home/signup'
  get 'about', to: 'home#about'
  get 'details', to: 'home#details'
  get 'signin', to: 'home#signin'
  get 'home/unverified_email'
  get 'home/register_successfull'
  get 'home/landing'
  
  get 'error/general_error'
  
  post 'home/signup_user', :to => 'home#signup_user', :as => :home_signup_user
  put 'user/resend_verification_email/:id(.:format)', :to => 'user#resend_verification_email', :as => :user_resend_verification_email
  post 'articles/picture/:id(.:format)', :to => 'articles#upload_picture', :as => :article_upload_picture
  delete 'articles/picture/:id(.:format)', :to => 'articles#delete_picture', :as => :article_delete_picture
  post 'events/picture/:id(.:format)', :to => 'events#upload_picture', :as => :event_upload_picture
  delete 'events/picture/:id(.:format)', :to => 'events#delete_picture', :as => :event_delete_picture
  post 'photo_albums/picture/:id(.:format)', :to => 'photo_albums#upload_picture', :as => :photo_album_upload_picture
  delete 'photo_albums/picture/:id(.:format)', :to => 'photo_albums#delete_picture', :as => :photo_album_delete_picture

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  #Set the default layout for this controller, the views from this controller are available when the user is looged in
  layout 'application'
  @@images_directory = "UniversityOfMelbourne/Events"

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to retrieve and list all the events from the model by its owner id
--------------------------------------------------------------------------------------------------------------------------------
=end
  def index
    @menu='events' #Set the menu variable
    $title=t(:title_events) #Set the title variable
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    @page_aux = params[:page] #Retrieve the params from the query string
    @page = @page_aux =~ /\A\d+\z/ ? @page_aux.to_i : 0 #Validate if the page_aux param can be parsed as an integer, otherwise set it to cero
    resp = Event.all(session[:user],@page) #Retrieve all the events from the model
    if resp[0] #Validate if the response was successfull
      @events_list = resp[1] #Get the events list from the response
      @total_pages = resp[3].to_i #Get the total numer of pages from the response
      @previous_page = @page > 0 ? @page-1 : -1 #Calculate the previous page number, if we are at the first page, then it will set to minus one
      @next_page = @page+1 < @total_pages ? @page+1 : -1 #Calculate the next page number, if we are at the last page, then it will set to minus one
    elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      flash[:danger] = t(:event_list_error_flash) #Set the error message to the user
      redirect_to error_general_error_path #Redirect the user to the generic error page
    else 
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to redirect the user to the new event page
--------------------------------------------------------------------------------------------------------------------------------
=end
  def new
    @menu='events' #Set the menu variable
    $title=t(:title_new_event)  #Set the title variable
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
	  @event = Event.new #Set a new event object to be filled by the user form
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to redirect the user to the edit event page
--------------------------------------------------------------------------------------------------------------------------------
=end
  def edit
    @menu='events' #Set the menu variable
    $title=t(:title_edit_event)  #Set the title variable
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
	  resp = Event.find(params[:id],session[:user]) #Retrieve the event to update
    if resp[0] #Validate if the response was successfull
      @event = resp[1] #Set the event object to fill the edit form
    elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      flash[:danger] = t(:event_get_error_flash) #Set the error message for the user
      redirect_to events_path #Redirect the user to edit event page
    else 
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to create a new Event
--------------------------------------------------------------------------------------------------------------------------------
=end
  def create
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    @event = Event.new(event_params) #Create a new event object with the parameters set by the user in the create form
    resp = @event.save(session[:user]) #Save the new Event object
    if resp[0] #Validate if the response was successfull
      @event = resp[1] #Get the event object from the server response
      if !resp[2] #Validate if the photo creation was successfull
        flash[:warning] = t(:event_photo_creation_error_flash) #Set the error message for the user
      end
  	  flash[:success] = t(:event_creation_success_flash, event: @event.name) #Set the success message for the user
      redirect_to events_path #Redirect the user to the events list page
    elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      if(resp[1].kind_of?(Array)) #If the response was unsucessful, validate if it was caused by an invalid Event object sent to the model. If so the server would have returned an array with the errors
        flash[:warning] = Util.format_validation_errors(resp[1]) #Set the invalid object message for the user
      end
      flash[:danger] = t(:event_creation_error_flash) #Set the error message for the user
   	  @event = Event.new #Reset the Event object to an empty one
   	  redirect_to new_event_path #Redirect the user to the Event creation page
    else 
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to update an Event
--------------------------------------------------------------------------------------------------------------------------------
=end
  def update
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
	  resp = Event.find(params[:id],session[:user]) #Retrieve the original event object to update
    if resp[0] #Validate if the response was successfull
      @event = resp[1] #Set the event object to be updated
    elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      flash[:danger] = t(:event_get_error_flash) #Set the error message for the user
      redirect_to events_path #Redirect the user to the events list page
    else 
      return #If not force return to trigger the redirect of the check_session function
    end
    resp2 = @event.update_attributes(event_params,session[:user]) #Update the candidate object
    if resp2[0] #Validate if the response was successfull
      flash[:success] = t(:event_modification_success_flash, event: @event.name) #Set the success message for the user
      redirect_to events_path #Redirect the user to the events list page
    elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      if(resp[1].kind_of?(Array)) #If the response was unsucessful, validate if it was caused by an invalid Event object sent to the model. If so the server would have returned an array with the errors
        flash[:warning] = Util.format_validation_errors(resp[1]) #Set the invalid object message for the user
      end
      flash[:danger] = t(:event_modification_error_flash) #Set the error message for the user
      redirect_to edit_event_path #Redirect the user to the Event edition page
    else 
      return #If not force return to trigger the redirect of the check_session function
    end
    rescue #Error Handilng code
      general_error_redirection('Controller: '+params[:controller]+'.'+action_name,$!)
  end

=begin
--------------------------------------------------------------------------------------------------------------------------------
  Function to upload a picture owned by an event
--------------------------------------------------------------------------------------------------------------------------------
=end
  def upload_picture
    if !check_session #Validate if the user session is active
      return #If not force return to trigger the redirect of the check_session function
    end
    resp = Event.find(params[:id],session[:user]) #Retrieve the original event object to update
    if resp[0] #Validate if the response was successfull
      @event = resp[1] #Set the event object to be updated
    elsif validate_authorized_access(resp[1]) #If the response was unsucessful, validate if it was caused by unauthorized access to the app or expired session
      flash[:danger] = t(:event_get_error_flash) #Set the error message for the user
      redirect_to :back #Redirect the user to the previous page
    else 
      return #If not force return to trigger the redirect of the check_session function
    end
    resp2 = @event.upload_picture(event_params,session[:user]) #Upload the picture

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<% provide(:title, t(:title_edit_event)) %>

<%= form_for(@event, :url => event_path ,:html => {:method => :put}) do |f| %>

<div class="page" style="padding-top:0;">
  <header class="title_photoheader">
    <div class="title_menubar">
      <%= form_for(@event, :url => event_upload_picture_path ,:html => {:method => :post}) do |photo_f| %>
        <%= photo_f.file_field :picture, accept: "image/png,image/gif,image/jpeg" ,class: 'file_input_control', placeholder: t(:field_placeholder, field_name: t(:picture)).capitalize %>
        <button class="UI button capsule dark item" name="Publish">Upload Photo</button>
      <% end %>
      
      <% if false %>
        <button class="UI button capsule dark item" name="Publish">Clear Photo</button>
        <button class="UI button capsule dark item" name="Publish" style="margin-left: auto;">Delete</button>
        <button class="UI button capsule dark item" name="Publish">Save to Queue</button>
        <button class="UI button capsule dark item" name="Publish">Publish</button>
      <% end %>
    </div>
    <%= f.text_field :name, class: "UI editfield header", style: "width: 100%;", placeholder: t(:field_placeholder, field_name: t(:name)).capitalize %>
  </header>

  <div class="page_container">
    <nav class="menubar">

      <% if false %>
        <div class="item" style="">
          <button class="UI button fullheight blue" name="Button">Hide Notifications</button>
          <button class="UI button fullheight blue" name="Button">Hide Attendances</button>
        </div>
      <% end %>

      <div class="item" style="margin-left: auto;">
        <button class="UI button fullheight green" name="Button">Finish Editing</button>
      </div>
    </nav>

    <div class="UI separator light">
      <h6 style="margin-right:auto;">Location</h6>
      <% if false %>
        <button class="UI button icon plus green active" name="Button"></button>
        <button class="UI button icon delete red active" name="Button"></button>
      <% end %>
    </div>
    <%= f.text_field :location, class: "UI editfield location", style: "width: 100%;", placeholder: t(:field_placeholder, field_name: t(:location)).capitalize, value: @event.location.name %>

    <% if false %>
    <section class="module map">
      <div class="module_container">
        <div class="module_text">
          <h3>Melbourne Central</h3>
          <h6>Shopping Centre</h6>
          <hr>
          <p><em>211 La Trobe St<br>
          Melbourne VIC 3000</em>
          </p>
        </div>

        <div class="module_media">
          <div class="img_map">
          </div>
        </div>
      </div>
    </section>
    <% end %>

    <div class="UI separator light">
      <h6 style="margin-right:auto;">Organizer</h6>
    </div>
    <%= f.text_field :organizer, class: "UI editfield organizer", style: "width: 100%;", placeholder: t(:field_placeholder, field_name: t(:organizer)).capitalize %>

    <div class="UI separator light">
      <h6 style="margin-right:auto;">Organizer Email</h6>
    </div>
    <%= f.text_field :organizer_email, class: "UI editfield organizer-email", style: "width: 100%;", placeholder: t(:field_placeholder, field_name: t(:organizer_email)).capitalize %>

    <% if false %>
    <div class="UI separator light">
      <h6 style="margin-right:auto;">Subheader</h6>
    </div>
    <input class="UI editfield subheader" style="width:100%;" type="text" value="Election night alongside Victoria's best political broadcasters.">
    <% end %>

    <div class="UI separator light">
      <h6 style="margin-right:auto;">Description</h6>
    </div>
    <%= f.text_area :description, class: "UI editfield body", style: "width: 100%;", placeholder: t(:field_placeholder, field_name: t(:description)).capitalize %>


    <!--
        ##TODO## :: CLEAN UP
    -->
    <div class="UI separator light">
      <h6 style="margin-right:auto;">Schedule</h6>
    </div>

    <div class="form-group">
      <label class="form-field-label"><%=capitalize_as_title(t(:start_date))%></label>
      <hr class="form-field-hr">
      <div class="input-group date" id="dpk_start_date" >
        <span class="input-group-addon input-addon-left">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
        <input type="text" readonly="true" class="form-control date_field" placeholder="Enter date" name="event[start_date]" value="<%=@event.start_date%>">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group bootstrap-timepicker">
        <span class="input-group-addon input-addon-left"><i class="glyphicon glyphicon-time"></i></span>
        <input id="tpk_start_date" type="text" class="form-control time_picker" readonly="true" name="event[start_time]" value="<%=@event.start_time%>">
      </div>
    </div>
    <div class="form-group">
      <label class="form-field-label"><%=capitalize_as_title(t(:end_date))%></label>
      <hr class="form-field-hr">
      <div class="input-group date" id="dpk_end_date">
        <span class="input-group-addon input-addon-left">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
        <input type="text" readonly="true" class="form-control date_field" placeholder="Enter date" name="event[end_date]" value="<%=@event.end_date%>">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group bootstrap-timepicker">
        <span class="input-group-addon input-addon-left"><i class="glyphicon glyphicon-time"></i></span>
        <input id="tpk_end_date" type="text" class="form-control time_picker" readonly="true" name="event[end_time]" value="<%=@event.end_time%>">
      </div>
    </div>

  </div>
</div>

<% end %>


<%= javascript_include_tag "events_util" %>
<script type="text/javascript">
$('#tpk_start_date').timepicker({
    minuteStep: 5,
    showMeridian: false
  });
  $('#tpk_end_date').timepicker({
    minuteStep: 5,
    showMeridian: false
  });
  $("#dpk_start_date").datepicker({
    format: '<%=t(:date_format_javascript)%>',
    todayBtn: 'linked',
    autoclose: true
  });
  $("#dpk_end_date").datepicker({
    format: '<%=t(:date_format_javascript)%>',
    todayBtn: 'linked',
    autoclose: true
  });
</script>


<% if false %>
<div>
<%= form_for(@event, :url => event_path ,:html => {:method => :put}) do |f| %>
  <div id="form_header_background"></div>
  <div id="form_header">
    <div id="form_header_top">
      <%= link_to image_tag("home/Camera.png", alt:t(:choose_cover_back)) + capitalize_as_title(t(:choose_cover_back)) , '#', :class => "btn btn_choose_cover" %>
      <%= f.submit capitalize_as_title(t(:save_and_finish)), class: "btn btn-form btn_form_header" %>
    </div>
    <hr>
    <%= f.text_field :name, class: "form-control text_field title_text_field", placeholder: t(:field_placeholder, field_name: t(:name)).capitalize %>
  </div>
  <div id="form_main">
    <div class="form-group">
    <label class="form-field-label"><%=capitalize_as_title(t(:location))%></label>
    <hr class="form-field-hr">
    <%= f.text_field :location, class: "form-control", placeholder: t(:field_placeholder, field_name: t(:location)).capitalize, value: @event.location.name %>
  </div>
  <div class="form-group">
    <label class="form-field-label"><%=capitalize_as_title(t(:start_date))%></label>
    <hr class="form-field-hr">
    <div class="input-group date" id="dpk_start_date" >
      <span class="input-group-addon input-addon-left">
        <i class="glyphicon glyphicon-calendar"></i>
      </span>
      <input type="text" readonly="true" class="form-control date_field" placeholder="Enter date" name="event[start_date]" value="<%=@event.start_date%>">
    </div>
  </div>
  <div class="form-group">
    <div class="input-group bootstrap-timepicker">
      <span class="input-group-addon input-addon-left"><i class="glyphicon glyphicon-time"></i></span>
      <input id="tpk_start_date" type="text" class="form-control time_picker" readonly="true" name="event[start_time]" value="<%=@event.start_time%>">
    </div>
  </div>
  <div class="form-group">
    <label class="form-field-label"><%=capitalize_as_title(t(:end_date))%></label>
    <hr class="form-field-hr">
    <div class="input-group date" id="dpk_end_date">
      <span class="input-group-addon input-addon-left">
        <i class="glyphicon glyphicon-calendar"></i>
      </span>
      <input type="text" readonly="true" class="form-control date_field" placeholder="Enter date" name="event[end_date]" value="<%=@event.end_date%>">
    </div>
  </div>
  <div class="form-group">
    <div class="input-group bootstrap-timepicker">
      <span class="input-group-addon input-addon-left"><i class="glyphicon glyphicon-time"></i></span>
      <input id="tpk_end_date" type="text" class="form-control time_picker" readonly="true" name="event[end_time]" value="<%=@event.end_time%>">
    </div>
  </div>
  <div class="form-group">
    <label class="form-field-label"><%=capitalize_as_title(t(:description))%></label>
    <hr class="form-field-hr">
    <%= f.text_area :description, class: "form-control text_area", placeholder: t(:field_placeholder, field_name: t(:description)).capitalize %>
  </div>
  <div class="form-group">
    <label class="form-field-label"><%=capitalize_as_title(t(:organizer))%></label>
    <hr class="form-field-hr">
    <%= f.text_field :organizer, class: "form-control text_field", placeholder: t(:field_placeholder, field_name: t(:organizer)).capitalize %>
  </div>
  <div class="form-group">
    <label class="form-field-label"><%=capitalize_as_title(t(:organizer_email))%></label>
    <hr class="form-field-hr">
    <%= f.text_field :organizer_email, class: "form-control text_field", placeholder: t(:field_placeholder, field_name: t(:organizer_email)).capitalize %>
  </div>
  <!--div class="form-group">
    <%= f.label t(:volunteers).capitalize%>
    <ul class="list-group" id="volunteers_list">
      <% @index = 0 %>
      <% @event.volunteers.each do |volunteer| %>
        <div class="list-group-item">
          <p><label><%= t(:position_title).capitalize + ': ' + volunteer.position_title%></label></p>
          <label><%= t(:description).capitalize + ': ' + volunteer.description%></label>
          <span class="badge btn_remove_volunteer" id="btn_remove_volunteer"><%=t(:remove).capitalize%></span>
          <input type="hidden" id="hdd_volunteer_index" class="hdd_volunteer_index" value=<%=@index%> />
        </div>
        <% @index = @index + 1 %>
      <% end %>
    </ul>
    <label><%= t(:position_title).capitalize%>: </label>
    <input type="text" class="form-control" id="txt_volunteer_position" placeholder="<%=t(:field_placeholder, field_name: t(:position_title)).capitalize%>"/>
    <label><%= t(:description).capitalize%>: </label>
    <input type="textarea" class="form-control" id="txt_volunteer_description" placeholder="<%=t(:field_placeholder, field_name: t(:description)).capitalize%>"/>
    <input type="button" class="btn btn-xs btn-info" id="btn_add_volunteer" value="<%=t(:add).capitalize%>"/>
    <%= f.hidden_field :volunteers, id: "hdd_volunteers", :value=> @event.volunteers.to_json%>
  </div-->
  <% end %>
  <br>
  </div>
  <div id="upload_pic_form">
  <%= form_for(@event, :url => event_upload_picture_path ,:html => {:method => :post}) do |f| %>
    <div class="form-group">
      <label class="form-field-label"><%=capitalize_as_title(t(:picture))%></label>
      <hr class="form-field-hr">
      <% @event.picture.each do |picture| %>
        <%= image_tag picture["url"], class: "event_image"%>
        <%= link_to t(:delete).capitalize, event_delete_picture_path(:id => picture["nodeId"]), method: :delete, :class => 'delete_link' %>
      <%end%>
    </div>
    <input type="hidden" id="hdd_previous_picture" name="event[previous_picture]" value="<%=@event.picture.blank? ? nil : @event.picture[0].to_json%>">
    <div class="form-group">
      <label class="form-field-label"><%=capitalize_as_title(t(:upload_new_picture))%></label>
      <hr class="form-field-hr">
      <div class="file_input_wrapper">
        <%= f.file_field :picture, accept: "image/png,image/gif,image/jpeg" ,class: 'file_input_control', placeholder: t(:field_placeholder, field_name: t(:picture)).capitalize %>
        <input class="btn btn-form file_input_button" type="button" value="<%=capitalize_as_title(t(:browse)) %>" name="commit">
      </div>
    </div>
    <div class="upload-preview">
      <!--label><%=capitalize_as_title(t(:picture_preview))%></label-->
      <!--Image closing tag required by the upload-preview-->
      <img />
    </div>
    <%= f.submit capitalize_as_title(t(:upload)), class: "btn btn-form" %>
    <% end %>
    </div>
  <div hidden="true">
    <div class="list-group-item" id="volunteers_list_item">
      <p><label><%= t(:position_title).capitalize%>:</label><label id="lbl_volunteers_position"></label></p>
      <label><%= t(:description).capitalize%>:</label><label id="lbl_volunteers_description"></label>
      <span class="badge" id="btn_remove_volunteer"><%=t(:remove).capitalize%></span>
      <input type="hidden" id="hdd_volunteer_index" class="hdd_volunteer_index"/>
    </div>
  </div>
</div>
<% end %>

app/views/events/index.html.erb
<div id="events_list">
  <% @events_list.each do |event| %>

    <section class="module news">
    <div class="module_container">
      <% if not event.picture[0].blank? %>
        <div class="module_media">
          <%= image_tag event.picture.blank? ? '' : event.picture[0]["url"], class: "img_tile", alt: t(:picture) %>
        </div>
      <% end %>

      <div class="module_text">
        <h3><%= event.name %></h3>
        <h4><%= event.location.name %></h4>
        <h4>
          <%= event.start_date %>
          <% if event.end_date != event.start_date %>
            – <%= event.end_date %>
          <% end %>
        </h4>

        <hr style="visibility: hidden;">

        <ul>
          <li>Added by <%= event.organizer %></li>
        </ul>
      </div>

      <%= button_to '', event_path(:id => event.id), confirm: 'Are you sure?', method: :delete, class: "UI button icon delete red" %>
      <%= link_to '<button class="UI button icon info blue" name="Button"></button>'.html_safe, edit_event_path(:id => event.id) %>
    </div>
  </section>

  <% end %>
</div>

<div class="section_controls">
  <%= render "partials/admin_list_pagination" %>
</div>